# This is a Docker Compose file for local development.
services:
  zensical:
    image: python:3.13-slim
    ports:
      - "8766:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: sh -c "pip install --no-cache-dir -r requirements.txt && zensical serve --dev-addr=0.0.0.0:8000"
    restart: unless-stopped
