# This is a Docker Compose file for local development.
services:
  docs:
    image: node:22-alpine
    ports:
      - "6173:3000"
    volumes:
      - ./docs:/project
    working_dir: /project
    restart: unless-stopped
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --port 3000"
