#!/bin/bash
# SPDX-FileCopyrightText: 2026 Marcus Baw and Baw Medical Ltd
# SPDX-License-Identifier: AGPL-3.0-or-later

# set -v  # Enable verbose mode
set -e  # Exit on error

# scripts may need to be made executable on some platforms before they can be run
# chmod +x s/<filename> is the command to do this on unixy systems

repo_root="$(cd "$(dirname "$0")/.." && pwd)"

cargo build -p gitehr

cd "$repo_root/gui"

WEBKIT_DISABLE_DMABUF_RENDERER=1 npm run tauri dev
