#!/bin/bash
# SPDX-FileCopyrightText: 2026 Marcus Baw and Baw Medical Ltd
# SPDX-License-Identifier: AGPL-3.0-or-later

# set -v  # Enable verbose mode
set -e  # Exit on error

# scripts may need to be made executable on some platforms before they can be run
# chmod +x s/<filename> is the command to do this on unixy systems

# installs the CLI binary from the workspace's cli/ crate
cargo install --path cli
