#!/bin/bash

# set -v  # Enable verbose mode
set -e  # Exit on error

# scripts may need to be made executable on some platforms before they can be run
# chmod +x s/<filename> is the command to do this on unixy systems

# bumps the Cargo package version (patch)
cargo set-version --bump patch
