#!/bin/bash

# set -v  # Enable verbose mode
set -e  # Exit on error

# UNIX based systems may require special permissions to run this file
# run chmod +x s/<filename> to allow this

# starts up the docker compose development environment
docker compose up